# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdvancedProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdvancedProject

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'RealmSwift'
pod 'Alamofire', '~> 4.8.2'
pod 'AlamofireObjectMapper'


end
